export const skillGroups = {
  "Операционные системы": ["Windows", "macOS", "Linux", "iOS", "Android"],
  "Языки программирования": [
    "JavaScript",
    "Python",
    "Java",
    "C#",
    "TypeScript",
    "C",
    "C++",
    "PHP",
    "Ruby",
    "Go",
  ],
  "Фреймворки и библиотеки": [
    "React",
    "Redux",
    "NextJS",
    "React-hook-form",
    "Formik",
    "NodeJS",
    "Styled-components",
    "Material UI",
    "GraphQL",
  ],
  "Технологии программирования": ["HTML5", "CSS", "SCSS", "Webpack", "Rollup"],
  "Среды разработки": ["Visual Studio Code", "WebStorm"],
  Tестирование: ["Jest", "Cypress", "React Testing Library"],
  "Системы контроля версий": ["Git"],
};
